branch-defaults:
  main:
    environment: flask-cd-env
    group_suffix: null
global:
  application_name: flask-cd
  branch: null
  default_ec2_keyname: aws-eb-cd
  default_platform: Python 3.7
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
